import { StyleSheet } from 'react-native';
import { SPIRITUAL_COLORS } from '@/constants/SpiritualColors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  gradient: { flex: 1 },
  keyboardView: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingTop: 88,
    paddingHorizontal: 24,
    paddingBottom: 48,
  },
  titleBlock: {
    alignItems: 'center',
    marginBottom: 28,
  },
  titleLine1: {
    fontSize: 11,
    letterSpacing: 3.5,
    textTransform: 'uppercase',
    color: SPIRITUAL_COLORS.accent,
    fontWeight: '600',
    marginBottom: 4,
  },
  titleLine2: {
    fontSize: 34,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
    letterSpacing: 0.5,
    lineHeight: 40,
  },
  panel: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(193,127,60,0.15)',
    paddingVertical: 28,
    paddingHorizontal: 24,
  },
  panelLabel: {
    fontSize: 12,
    color: SPIRITUAL_COLORS.accent,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 16,
  },
  input: {
    width: '100%',
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 12,
    marginBottom: 12,
    fontSize: 16,
    color: SPIRITUAL_COLORS.foreground,
    borderWidth: 1,
    borderColor: SPIRITUAL_COLORS.border,
  },
  inputError: {
    borderColor: SPIRITUAL_COLORS.spiritualRed,
  },
  errorBox: {
    width: '100%',
    backgroundColor: '#FDE8E8',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: SPIRITUAL_COLORS.spiritualRed,
  },
  errorText: {
    fontSize: 14,
    color: SPIRITUAL_COLORS.spiritualRed,
    marginBottom: 12,
  },
  goToSignUpButton: {
    backgroundColor: SPIRITUAL_COLORS.primary,
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 12,
    alignItems: 'center',
  },
  goToSignUpButtonText: {
    color: SPIRITUAL_COLORS.primaryForeground,
    fontSize: 15,
    fontWeight: '600',
  },
  loginButton: {
    width: '100%',
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 14,
    shadowColor: '#8b4513',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  loginButtonGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
  },
  loginButtonText: {
    color: SPIRITUAL_COLORS.primaryForeground,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  signUpLink: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  signUpLinkText: {
    color: SPIRITUAL_COLORS.secondary,
    fontSize: 14,
    letterSpacing: 0.3,
  },
  signUpLinkBold: {
    fontWeight: '700',
  },
  footerTagline: {
    fontSize: 10,
    color: 'rgba(139,69,19,0.5)',
    letterSpacing: 0.5,
    marginTop: 24,
    textAlign: 'center',
  },
});
