workflows:
  ios-workflow:
    name: iOS Spiritual App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        # Environment variables to prevent shell issues
        EXPO_NO_FLIPPER: "1"
        RCT_NEW_ARCH_ENABLED: "0"
        SHELL: "/bin/bash"
        BASH_SILENCE_DEPRECATION_WARNING: "1"
        CI: "true"
        # Prevent dotenv issues
        EXPO_NO_DOTENV: "1"
      groups:
        - expo
      node: 20.19.4
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli eas-cli
          npm install --legacy-peer-deps
      - name: Fix expo-constants PhaseScriptExecution error
        script: |
          # Apply the fix from your research - comment out 'set -eo pipefail'
          if [ -f "node_modules/expo-constants/scripts/get-app-config-ios.sh" ]; then
            echo "Applying expo-constants fix..."
            sed -i '' 's/^set -eo pipefail/#set -eo pipefail/' node_modules/expo-constants/scripts/get-app-config-ios.sh
            echo "✅ expo-constants fix applied"
          else
            echo "⚠️ expo-constants script not found"
          fi
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --clean
      - name: Patch iOS Pod settings
        script: |
          # Try Node.js script first, fallback to direct sed approach
          if ! node scripts/patch-ios-pods.js; then
            echo "Node script failed, using direct Podfile patch..."
            cd ios
            
            # Ensure platform is set
            if ! grep -q "platform :ios" Podfile; then
              sed -i '' '1i\
platform :ios, '\''12.0'\''
' Podfile
            fi
            
            # Add post_install hook if not present
            if ! grep -q "post_install do" Podfile; then
              cat >> Podfile << 'EOF'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      if config.name == 'Debug'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
EOF
            fi
            
            echo "✅ Direct Podfile patch completed"
          fi
      - name: Pod install
        script: |
          cd ios && pod install
      - name: Post-pod install patch
        script: |
          # Patch the generated Pods project directly
          if [ -f "ios/Pods/Pods.xcodeproj/project.pbxproj" ]; then
            echo "Patching Pods Xcode project..."
            cd ios/Pods/Pods.xcodeproj
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' project.pbxproj
            sed -i '' 's/SWIFT_VERSION = [^;]*/SWIFT_VERSION = 5.0/g' project.pbxproj
            echo "✅ Pods project patched"
          fi
      - name: Build iOS with Xcode
        script: |
          # Build directly with Xcode (bypassing EAS entirely)
          cd ios
          echo "Listing available workspaces and schemes..."
          ls -la
          xcodebuild -workspace SpiritualApp.xcworkspace -scheme SpiritualApp -configuration Release -destination 'generic/platform=iOS Simulator' build
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log