workflows:
  ios-workflow:
    name: iOS Spiritual App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        # Environment variables to prevent shell issues
        EXPO_NO_FLIPPER: "1"
        RCT_NEW_ARCH_ENABLED: "0"
        SHELL: "/bin/bash"
        BASH_SILENCE_DEPRECATION_WARNING: "1"
        CI: "true"
        # Prevent dotenv issues
        EXPO_NO_DOTENV: "1"
      groups:
        - expo
      node: 20.19.4
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli eas-cli
          npm install --legacy-peer-deps
      - name: Fix expo-constants PhaseScriptExecution error
        script: |
          # Apply the fix from your research - comment out 'set -eo pipefail'
          if [ -f "node_modules/expo-constants/scripts/get-app-config-ios.sh" ]; then
            echo "Applying expo-constants fix..."
            sed -i '' 's/^set -eo pipefail/#set -eo pipefail/' node_modules/expo-constants/scripts/get-app-config-ios.sh
            echo "✅ expo-constants fix applied"
          else
            echo "⚠️ expo-constants script not found"
          fi
      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --clean
      - name: Patch iOS Pod settings
        script: |
          echo "Patching Podfile for iOS 12.0 deployment target..."
          cd ios
          
          # Backup original Podfile
          cp Podfile Podfile.backup
          
          # Check if post_install already exists
          if grep -q "post_install do" Podfile; then
            echo "⚠️  post_install hook already exists, skipping Podfile modification"
            echo "Will patch Pods project directly after pod install"
          else
            # Ensure platform is set to iOS 12.0
            if grep -q "platform :ios" Podfile; then
              sed -i '' "s/platform :ios, '[^']*'/platform :ios, '12.0'/" Podfile
              echo "✅ Updated platform to iOS 12.0"
            else
              # Add platform at the top
              echo "platform :ios, '12.0'" | cat - Podfile > Podfile.tmp && mv Podfile.tmp Podfile
              echo "✅ Added platform iOS 12.0"
            fi
            
            # Add post_install hook at the end
            cat >> Podfile << 'PODFILE_END'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      if config.name == 'Debug'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
PODFILE_END
            echo "✅ Added post_install hook"
          fi
          
          # Show the last few lines to verify
          echo "=== Last 10 lines of Podfile ==="
          tail -10 Podfile
          echo "================================"
      - name: Pod install
        script: |
          cd ios && pod install
      - name: Post-pod install patch
        script: |
          # Patch the generated Pods project directly
          if [ -f "ios/Pods/Pods.xcodeproj/project.pbxproj" ]; then
            echo "Patching Pods Xcode project..."
            cd ios/Pods/Pods.xcodeproj
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' project.pbxproj
            sed -i '' 's/SWIFT_VERSION = [^;]*/SWIFT_VERSION = 5.0/g' project.pbxproj
            echo "✅ Pods project patched"
          fi
      - name: Build iOS with Xcode
        script: |
          # Build directly with Xcode (bypassing EAS entirely)
          cd ios
          echo "Listing available workspaces and schemes..."
          ls -la
          xcodebuild -workspace SpiritualApp.xcworkspace -scheme SpiritualApp -configuration Release -destination 'generic/platform=iOS Simulator' build
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log