import { Dimensions, StyleSheet } from 'react-native';
import { SPIRITUAL_COLORS, SPIRITUAL_SHADOWS } from '@/constants/SpiritualColors';

const { height: screenHeight } = Dimensions.get('window');
const MONTH_MODAL_MAX_HEIGHT = screenHeight - 140;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: SPIRITUAL_COLORS.background },
  gradient: { flex: 1 },
  safeArea: { flex: 1 },
  glowOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 280,
    backgroundColor: 'rgba(193,127,60,0.06)',
    zIndex: 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: SPIRITUAL_COLORS.textMuted,
  },
  scrollView: { flex: 1 },
  scrollContent: {
    paddingBottom: 120,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  header: {
    paddingVertical: 14,
    paddingHorizontal: 4,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(193,127,60,0.12)',
  },
  headerLabel: {
    fontSize: 10,
    color: SPIRITUAL_COLORS.accent,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
  },
  headerSubtitle: {
    fontSize: 13,
    color: SPIRITUAL_COLORS.textMuted,
    fontStyle: 'italic',
    marginTop: 2,
  },
  heroCardWrap: {
    marginBottom: 20,
    borderRadius: 18,
    ...SPIRITUAL_SHADOWS.divine,
  },
  heroCard: {
    borderRadius: 18,
    padding: 18,
    paddingBottom: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  heroCardCircles: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 120,
    height: 120,
  },
  heroCircle1: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  heroCircle2: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  heroLabel: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.65)',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  heroTypePill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  heroTypePillText: {
    fontSize: 9,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.primaryForeground,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.primaryForeground,
    marginBottom: 10,
    lineHeight: 24,
  },
  heroMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  heroMetaText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  dividerMargin: {
    marginTop: 20,
    marginBottom: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(193,127,60,0.3)',
  },
  dividerLineRight: {},
  dividerText: {
    fontSize: 12,
    color: 'rgba(193,127,60,0.5)',
    letterSpacing: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  totalPill: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(193,127,60,0.1)',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 20,
  },
  totalPillText: {
    fontSize: 10,
    color: SPIRITUAL_COLORS.primary,
    fontWeight: '600',
  },
  allEventsList: {
    gap: 0,
  },
  eventPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(193,127,60,0.15)',
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  eventPillBar: {
    width: 3,
    height: 36,
    borderRadius: 2,
    marginRight: 10,
  },
  eventPillContent: {
    flex: 1,
    minWidth: 0,
  },
  eventPillHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  eventPillBadge: {
    alignSelf: 'flex-start',
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 20,
  },
  eventPillBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  eventPillTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
  },
  eventPillLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  eventPillLocationText: {
    fontSize: 11,
    color: SPIRITUAL_COLORS.textMuted,
    flex: 1,
  },
  eventPillRight: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  eventPillDate: {
    fontSize: 11,
    fontWeight: '600',
    color: SPIRITUAL_COLORS.primary,
  },
  eventPillTime: {
    fontSize: 11,
    color: SPIRITUAL_COLORS.textMuted,
    marginTop: 1,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  monthCard: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(193,127,60,0.15)',
    padding: 16,
    paddingTop: 14,
    minHeight: 120,
    position: 'relative',
    overflow: 'hidden',
  },
  monthCardCurrent: {
    backgroundColor: 'rgba(193,127,60,0.08)',
    borderWidth: 1.5,
    borderColor: 'rgba(193,127,60,0.35)',
    ...SPIRITUAL_SHADOWS.peaceful,
  },
  monthCardNow: {
    position: 'absolute',
    top: 8,
    right: 10,
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: SPIRITUAL_COLORS.primary,
    opacity: 0.8,
  },
  monthCardName: {
    fontSize: 15,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
  },
  monthCardYear: {
    fontSize: 11,
    color: SPIRITUAL_COLORS.accent,
    marginBottom: 10,
    opacity: 0.7,
  },
  monthCardPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 8,
  },
  monthCardPill: {
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  monthCardPillText: {
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  monthCardCount: {
    fontSize: 12,
    color: SPIRITUAL_COLORS.textMuted,
  },
  monthCardDots: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 8,
  },
  monthCardDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  monthCardEmpty: {
    fontSize: 11,
    fontStyle: 'italic',
    color: 'rgba(139,69,19,0.35)',
    marginTop: 4,
  },
  bottomPadding: {
    height: 24,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(30,10,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContentWrapper: {
    maxWidth: 420,
    width: '100%',
    alignSelf: 'center',
  },
  sheetContainer: {
    backgroundColor: SPIRITUAL_COLORS.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 48,
    ...SPIRITUAL_SHADOWS.divine,
  },
  monthSheetContainer: {
    height: MONTH_MODAL_MAX_HEIGHT,
    maxHeight: MONTH_MODAL_MAX_HEIGHT,
  },
  eventSheetContainer: {
    height: screenHeight * 0.88,
    maxHeight: screenHeight * 0.88,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    backgroundColor: 'rgba(193,127,60,0.3)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetYear: {
    fontSize: 10,
    color: SPIRITUAL_COLORS.accent,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  sheetMonthTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
    marginBottom: 16,
  },
  sheetScroll: { flex: 1, minHeight: 0 },
  sheetScrollContent: { paddingBottom: 24, flexGrow: 1 },
  noEventsMessage: {
    fontSize: 13,
    color: SPIRITUAL_COLORS.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 20,
  },
  eventSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  eventSheetTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
    marginRight: 12,
  },
  sheetCloseBtn: {
    padding: 4,
  },
  eventDetailBadge: {
    alignSelf: 'center',
    marginBottom: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  eventDetailMeta: {
    gap: 12,
    marginBottom: 24,
  },
  eventDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eventDetailMetaText: {
    fontSize: 16,
    color: SPIRITUAL_COLORS.foreground,
  },
  descriptionSection: {
    borderTopWidth: 1,
    borderTopColor: SPIRITUAL_COLORS.border,
    paddingTop: 20,
  },
  descriptionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: SPIRITUAL_COLORS.foreground,
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 16,
    color: SPIRITUAL_COLORS.textMuted,
    lineHeight: 24,
  },
  seeMoreButtonLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: SPIRITUAL_COLORS.primary,
    gap: 8,
  },
  seeMoreButtonTextLarge: {
    fontSize: 16,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.primaryForeground,
  },
  shareButtonContainer: {
    marginTop: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  shareButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    gap: 8,
  },
  shareButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: SPIRITUAL_COLORS.primaryForeground,
  },
});
