import { Dimensions, StyleSheet } from 'react-native';
import { SPIRITUAL_COLORS, SPIRITUAL_PALETTE, SPIRITUAL_SHADOWS } from '@/constants/SpiritualColors';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
    paddingHorizontal: 20,
  },
  header: {
    paddingTop: 56,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(139,69,19,0.12)',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  headerLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  omLogo: {
    width: 80,
    height: 80,
  },
  accountButton: {
    padding: 4,
  },
  dropdownBackdrop: {
    flex: 1,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 80,
    right: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 190,
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 18,
    gap: 10,
  },
  dropdownItemText: {
    fontFamily: 'DMSans_500Medium',
    fontSize: 15,
    color: SPIRITUAL_COLORS.foreground,
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.07)',
    marginHorizontal: 12,
  },
  hero: {
    paddingTop: 24,
    paddingBottom: 8,
    alignItems: 'center',
  },
  heroMainTitle: {
    fontFamily: 'LibreBaskerville_700Bold',
    fontSize: 26,
    color: SPIRITUAL_PALETTE.brown800,
    letterSpacing: 0.5,
    marginBottom: 6,
    textAlign: 'center',
  },
  heroSubTitle: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 17,
    color: SPIRITUAL_PALETTE.copper,
    letterSpacing: 0.4,
    marginBottom: 12,
    textAlign: 'center',
  },
  heroDescriptionWrap: {
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(193,127,60,0.4)',
    paddingLeft: 12,
    alignSelf: 'stretch',
    marginHorizontal: 8,
  },
  heroDescription: {
    fontFamily: 'DMSans_400Regular_Italic',
    fontSize: 14,
    color: SPIRITUAL_COLORS.textMuted,
    lineHeight: 22,
    textAlign: 'center',
  },
  heroImageContainer: {
    marginTop: 16,
    marginBottom: 4,
    borderRadius: 18,
    shadowColor: '#3b1a00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 6,
  },
  heroImageClip: {
    borderRadius: 18,
    overflow: 'hidden',
  },
  heroImage: {
    width: screenWidth - 40,
    height: screenWidth - 40,
  },
  divider: {
    textAlign: 'center',
    color: SPIRITUAL_PALETTE.brown300,
    fontSize: 16,
    marginVertical: 18,
    letterSpacing: 6,
  },
  dailyQuotesCard: {
    backgroundColor: SPIRITUAL_PALETTE.brown900,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 24,
    overflow: 'hidden',
    ...SPIRITUAL_SHADOWS.card,
  },
  dailyQuotesAccent: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
    height: 2,
    backgroundColor: SPIRITUAL_PALETTE.marigold,
    borderRadius: 1,
  },
  quoteContent: {
    minHeight: 60,
  },
  quoteScrollContent: {},
  quotePage: {
    paddingHorizontal: 4,
    minHeight: 60,
    justifyContent: 'center',
  },
  dailyQuoteText: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 16,
    color: SPIRITUAL_PALETTE.bg,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 8,
  },
  dailyQuoteAuthor: {
    fontFamily: 'DMSans_400Regular_Italic',
    fontSize: 12,
    color: 'rgba(251,243,231,0.65)',
    textAlign: 'center',
  },
  liveSlide: {
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  liveSlideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  liveSlideDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: SPIRITUAL_PALETTE.marigold,
    marginRight: 6,
  },
  liveSlideLabel: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 12,
    color: SPIRITUAL_PALETTE.marigold,
    letterSpacing: 1.5,
  },
  liveSlideTitle: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 16,
    color: SPIRITUAL_PALETTE.bg,
    textAlign: 'left',
    lineHeight: 22,
    marginBottom: 12,
  },
  liveSlideButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: SPIRITUAL_PALETTE.kumkum,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  liveSlideButtonText: {
    fontFamily: 'DMSans_700Bold',
    color: '#fff',
    fontSize: 14,
  },
  dailyQuotePlaceholder: {
    fontFamily: 'DMSans_400Regular_Italic',
    fontSize: 14,
    color: 'rgba(251,243,231,0.65)',
    textAlign: 'center',
  },
  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginTop: 14,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(251,243,231,0.25)',
  },
  dotActive: {
    width: 18,
    backgroundColor: SPIRITUAL_PALETTE.marigold,
  },
  sectionTitle: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 18,
    color: SPIRITUAL_COLORS.foreground,
    marginBottom: 14,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    width: (screenWidth - 52) / 2,
    marginBottom: 12,
    borderRadius: 14,
    overflow: 'hidden',
  },
  featureCardFullWidth: {
    width: '100%',
  },
  featureCardInner: {
    backgroundColor: SPIRITUAL_PALETTE.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: SPIRITUAL_PALETTE.brown200,
    paddingVertical: 16,
    paddingHorizontal: 14,
    minHeight: 120,
    position: 'relative',
    ...SPIRITUAL_SHADOWS.card,
  },
  featureAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 3,
    height: '40%',
    borderTopLeftRadius: 14,
  },
  featureIconWrap: {
    marginBottom: 8,
  },
  featureTitle: {
    fontFamily: 'DMSans_700Bold',
    fontSize: 13,
    color: SPIRITUAL_PALETTE.brown800,
    marginBottom: 4,
  },
  featureDescription: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 11,
    color: SPIRITUAL_COLORS.textMuted,
    lineHeight: 16,
  },
  bottomImageContainer: {
    marginTop: 12,
    borderRadius: 18,
    shadowColor: '#3b1a00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 6,
  },
  bottomImageClip: {
    borderRadius: 18,
    overflow: 'hidden',
  },
  bottomImage: {
    width: screenWidth - 40,
    height: (screenWidth - 40) * (306 / 514),
  },
  footerRow: {
    alignItems: 'center',
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: SPIRITUAL_PALETTE.brown200,
  },
  footerCopyright: {
    fontFamily: 'DMSans_600SemiBold',
    fontSize: 12,
    color: SPIRITUAL_PALETTE.brown500,
    letterSpacing: 0.3,
  },
  footerRights: {
    fontFamily: 'DMSans_400Regular',
    fontSize: 10,
    color: SPIRITUAL_PALETTE.brown400,
    marginTop: 2,
  },
  footerSpacer: {
    height: 24,
  },
});
