import { Dimensions, Platform, StyleSheet } from 'react-native';
import { SPIRITUAL_COLORS, SPIRITUAL_SHADOWS } from '@/constants/SpiritualColors';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
    paddingHorizontal: 20,
  },
  header: {
    paddingTop: 56,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(139,69,19,0.12)',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  headerLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  omLogo: {
    width: 80,
    height: 80,
  },
  accountButton: {
    padding: 4,
  },
  dropdownBackdrop: {
    flex: 1,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 80,
    right: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    minWidth: 190,
    overflow: 'hidden',
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 18,
    gap: 10,
  },
  dropdownItemText: {
    fontSize: 15,
    fontWeight: '500',
    color: SPIRITUAL_COLORS.foreground,
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.07)',
    marginHorizontal: 12,
  },
  hero: {
    paddingTop: 24,
    paddingBottom: 8,
    alignItems: 'center',
  },
  heroMainTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1C0000',
    letterSpacing: 0.5,
    marginBottom: 6,
    textAlign: 'center',
  },
  heroSubTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#b5651d',
    letterSpacing: 0.4,
    marginBottom: 12,
    textAlign: 'center',
  },
  heroDescriptionWrap: {
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(193,127,60,0.4)',
    paddingLeft: 12,
    alignSelf: 'stretch',
    marginHorizontal: 8,
  },
  heroDescription: {
    fontSize: 14,
    color: SPIRITUAL_COLORS.textMuted,
    fontStyle: 'italic',
    lineHeight: 22,
    textAlign: 'center',
  },
  divider: {
    textAlign: 'center',
    color: 'rgba(139,69,19,0.3)',
    fontSize: 16,
    marginVertical: 18,
    letterSpacing: 6,
  },
  dailyQuotesCard: {
    backgroundColor: Platform.select({ android: '#fdfaf5', default: 'rgba(255,255,255,0.7)' }),
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(193,127,60,0.2)',
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 24,
    ...Platform.select({ ios: { overflow: 'hidden' as const } }),
    ...SPIRITUAL_SHADOWS.card,
  },
  dailyQuotesAccent: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
    height: 2,
    backgroundColor: SPIRITUAL_COLORS.primary,
    borderRadius: 1,
  },
  dailyQuotesLabel: {
    fontSize: 10,
    color: SPIRITUAL_COLORS.accent,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
  },
  quoteContent: {
    minHeight: 60,
  },
  quoteScrollContent: {},
  quotePage: {
    paddingHorizontal: 4,
    minHeight: 60,
    justifyContent: 'center',
  },
  dailyQuoteText: {
    fontSize: 16,
    color: '#5a2d0c',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 8,
    fontWeight: '600',
  },
  dailyQuoteAuthor: {
    fontSize: 12,
    color: SPIRITUAL_COLORS.textMuted,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  liveSlide: {
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  liveSlideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  liveSlideDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff0000',
    marginRight: 6,
  },
  liveSlideLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ff0000',
    letterSpacing: 1.5,
  },
  liveSlideTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#5a2d0c',
    textAlign: 'left',
    lineHeight: 22,
    marginBottom: 12,
  },
  liveSlideButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#a30000',
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  liveSlideButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  dailyQuotePlaceholder: {
    fontSize: 14,
    color: SPIRITUAL_COLORS.textMuted,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  dots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    marginTop: 14,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(193,127,60,0.25)',
  },
  dotActive: {
    width: 18,
    backgroundColor: SPIRITUAL_COLORS.primary,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: SPIRITUAL_COLORS.foreground,
    marginBottom: 14,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    width: (screenWidth - 52) / 2,
    marginBottom: 12,
    borderRadius: 14,
    ...Platform.select({ ios: { overflow: 'hidden' as const } }),
  },
  featureCardFullWidth: {
    width: '100%',
  },
  featureCardInner: {
    backgroundColor: Platform.select({ android: '#fdf9f3', default: 'rgba(255,255,255,0.65)' }),
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(193,127,60,0.18)',
    paddingVertical: 16,
    paddingHorizontal: 14,
    minHeight: 120,
    position: 'relative',
    ...SPIRITUAL_SHADOWS.card,
  },
  featureAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 3,
    height: '40%',
    borderTopLeftRadius: 14,
  },
  featureIconWrap: {
    marginBottom: 8,
  },
  featureTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
  },
  featureDescription: {
    fontSize: 11,
    color: SPIRITUAL_COLORS.textMuted,
    lineHeight: 16,
  },
  gurudevSaysCard: {
    marginTop: 24,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: Platform.select({ android: '#fcf6ee', default: 'rgba(255,255,255,0.5)' }),
    borderWidth: 1,
    borderColor: 'rgba(193,127,60,0.2)',
  },
  gurudevSaysLabel: {
    fontSize: 10,
    color: SPIRITUAL_COLORS.accent,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 8,
    textAlign: 'center',
  },
  gurudevSaysText: {
    fontSize: 14,
    color: '#5a2d0c',
    fontStyle: 'italic',
    lineHeight: 22,
    textAlign: 'center',
  },
  gurudevSaysAuthor: {
    fontSize: 11,
    color: SPIRITUAL_COLORS.accent,
    marginTop: 8,
    textAlign: 'center',
  },
  footerSpacer: {
    height: 24,
  },
});
